version: '2'
services:
    api:
        build: api
        ports:
        - "9001:9001"
    web:
        build: web
        ports:
        - "80:80"
        links: 
        - mongo
    mongo:
        image: "mongo"