version: '2'
services:
    api:
        build: api
        ports:
        - "8083:8083"
    web:
        build: web
        ports:
        - "8084:8084"
        links: 
        - mongo
    mongo:
        image: "mongo"